mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^winit/', include('winit.urls', namespace="winit")),
    url(r'^$', 'winit.views.home',name='home'),
    url(r'^admin/', include(admin.site.urls)),

]
# from django.conf.urls import patterns, include, url


# urlpatterns = patterns('',
#    url(r'^$', include('winit.urls', namespace="winit", app_name="winit")),
# )

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^winit/', include('winit.urls', namespace="winit")),
    url(r'^$', 'winit.views.home',name='home'),
    url(r'^admin/', include(admin.site.urls)),
]
# from django.conf.urls import patterns, include, url


# urlpatterns = patterns('',
#    url(r'^$', include('winit.urls', namespace="winit", app_name="winit")),
# )

mysite/winit/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('',
   url(r'^$', 'winit.views.home', name='home'),
   url(r'^comp/$', 'winit.views.comp', name='comp'),
   url(r'^tc/$','winit.views.tc',name='tc'),
   url(r'^disc/$','winit.views.disc',name='disc'),
   url(r'^registered/$', 'winit.views.store', name='store'),
   url(r'^signin/$','winit.views.check', name='checkin'),
   url(r'^start/$','winit.views.start', name='start'),
   url(r'^start/exam/$','winit.views.exam', name='exam'),
   url(r'^thanku/$','winit.views.thanku',name='thanku'),
   url(r'^answer/$','winit.views.answer',name='answer')   
)

mysite/winit/models.py
from django.db import models
from django.utils.encoding import smart_unicode
import datetime

# Create your models here.
class Registration(models.Model):

	Firstname = models.CharField(max_length = 30,null = True,blank = True)
	Lastname = models.CharField(max_length = 30,null = True,blank = True)
	dateofbirth = models.DateField(max_length = 30,blank = True, null = True)
	address = models.CharField(max_length = 50,null = True,blank = True)
	# gender = models.CharField(max_length = 10, choices = GENDER_CHOICE, null = True, blank = True)
	email = models.EmailField()
	username = models.CharField(max_length = 30,blank = True, primary_key=True)
	password=models.CharField(max_length=20)
	contactnumber = models.CharField(max_length=12)
	def __unicode__(self):
		return smart_unicode(self.email)

class Topic(models.Model):
	topic = models.CharField(max_length = 300, primary_key=True)
	def __unicode__(self):
		return smart_unicode(self.topic)

class Question(models.Model):
	queno =  models.IntegerField(primary_key=True)
	question = models.CharField(max_length = 50)
	topic = models.ForeignKey(Topic)

class Userdata(models.Model):
	queno = models.ForeignKey(Question)
	username = models.ForeignKey(Registration)
	answer = models.TextField(max_length = 500)
	date = models.DateField()
	score = models.IntegerField(default = 0)

		

mysite/winit/views.py
from django.shortcuts import render,render_to_response
from .models import Registration,Question,Userdata
import datetime
from django.http import HttpResponse
def home(request):
	return render(request,"mystyle.html")
	# fields = '__all__'
def comp(request):
	return render(request,"competitions.html")
def tc(request):
	return render(request,"termsandconditions.html")
def disc(request):
	return render(request,"disclaimer.html")
def start(request):
	username =  request.POST.get("username")
	# top = Topic.objects.all()
	return render(request,"start.html",{"username":username})
		#{"top":top})

def answer(request):
	text = {}
	if request.method == "POST":
		Ans = request.POST.get('essay','')
		queno = int(request.POST.get('qno',''))
		queno = Question.objects.get(queno = queno)
		username = str(request.POST.get('username',''))
		username = Registration.objects.get(username = username)
		date = datetime.datetime.now()
		score = 0
		data = Userdata(queno=queno,username=username,answer=Ans,date=date,score=score)
		data.save()
	return render(request,"thanku.html")

def thanku(request):
	return render(request,"thanku.html")
def exam(request):
	username = request.POST.get('username','')
	question = Question.objects.all().order_by('?')[:1]
	return render(request,"exam.html",{'question':question,'username':username})
def store(request):
	context = {}
	if request.method =="POST" :
		Firstname = request.POST.get('fname','')
		Lastname = request.POST.get('lname','')
		d = request.POST.get('dob','')
		dateofbirth = datetime.datetime.strptime(d,"%Y-%m-%d").date()
		address = request.POST.get('addr','')
		email = request.POST.get('usremail','')
		username = request.POST.get('username','')
		password = request.POST.get('password','')
		contactnumber =  request.POST.get('number','')
		# context['fname'] = Firstname
		similar = Registration.objects.filter(username = username)
		if similar:
			context['error']='Username already exists'
			return render(request,"signup.html",context)
		else:
			obj = Registration(Firstname=Firstname,Lastname=Lastname,dateofbirth=dateofbirth,address=address,
					email=email,username=username,password=password,contactnumber=contactnumber)
			obj.save()
			return render(request,"signin.html")
	else :
		return render(request,"signup.html",context)

def check(request):
	context = {}
	if request.method == 'POST':
		username = request.POST.get('username','')
		password = request.POST.get('password','')
		similar = Registration.objects.get(username = username)
		if similar:
			if similar.password == password:
				return render(request,"Rules.html",{"username":username})
		else:
			context['error'] = 'Inavlid username or password'
	return render(request,'signin.html',context)
# Create your views here.

mysite/templates/Home.html
<!-- Latest compiled and minified CSS -->
<html>
<head>
<link rel="stylesheet" href="bootstrap.min.css">

<!-- jQuery library -->
<script src="jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="bootstrap.min.js"></script>


	<link rel = "stylesheet" type = "text/css" href="styles.css">
</head>
<body>
	<div class = "main">
		<div class = "title">
			<div class = "titles_img">
				<img src ="1.jpg" width = "100%" height="25%"></div>
			<div class = "icon_comp">
				<img src="winit.gif" width="60%" height="20%"></div>
			<div class = "pins" >
				<div class="btn-group">
				  <button type="button" class="btn btn-link btn-lg">COMPETITIONS</button>
				  <button type="button" class="btn btn-link btn-lg"> ABOUT US </button>
				  <button type="button" class="btn btn-link btn-lg">WINNER'S GALLERY</button></div>			
			</div>	
			<div class = "status" align="right">
				<div class = "login">
						<a href = "login.html"><img src= "7.png" width = "85%" height ="6%"></a>
				</div>
				<div class = "sign_up">
					<a href = "signup.html"><img src = "8.png" width = "85%" height ="6%">
					</a>
				</div>
			</div>	
		</div>
		<div class = "mainbody">
			<img src = "9.jpg" width="100%"></div>		
			<div class = "body">
				<div class="btn-group">
				  <button type="button" class="btn btn-link btn-lg"> Terms And Conditions |</button>
				  <button type="button" class="btn btn-link btn-lg"> Disclaimer |</button>
				  <button type="button" class="btn btn-link btn-lg"> About Us </button></div>	
			</div> 

	</div>
</body>
</html>

mysite/templates/Register.html
<!-- Latest compiled and minified CSS -->
<html>
<head>
<link rel="stylesheet" href="bootstrap.min.css">

<!-- jQuery library -->
<script src="jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="bootstrap.min.js"></script>


	<link rel = "stylesheet" type = "text/css" href="styles.css">
</head>
<body>
	<div class = "main">
		<div class = "title">
			<div class = "titles_img">
				<img src ="1.jpg" width = "100%" height="25%"></div>
			<div class = "icon_comp">
				<img src="winit.gif" width="60%" height="20%"></div>
			<div class = "pins" >
				<div class="btn-group">
				  <button type="button" class="btn btn-link btn-lg">COMPETITIONS</button>
				  <button type="button" class="btn btn-link btn-lg"> ABOUT US </button>
				  <button type="button" class="btn btn-link btn-lg">WINNER'S GALLERY</button></div>			
			</div>	
			<div class = "status" align="right">
				<div class = "login">
						<a href = "login.html"><img src= "7.png" width = "85%" height ="6%"></a>
				</div>
				<div class = "sign_up">
					<a href = "signup.html"><img src = "8.png" width = "85%" height ="6%">
					</a>
				</div>
			</div>	
		</div>
		<div class = "mainbody">
			<img src = "9.jpg" width="100%"></div>		
			<div class = "body">
				<div class="btn-group">
				  <button type="button" class="btn btn-link btn-lg"> Terms And Conditions |</button>
				  <button type="button" class="btn btn-link btn-lg"> Disclaimer |</button>
				  <button type="button" class="btn btn-link btn-lg"> About Us </button></div>	
			</div> 

	</div>
</body>
</html>

mysite/templates/Rules.html
<html>
<head>
	{%load staticfiles%}
	<link rel = "stylesheet" href="{%static 'winit/Css/Rules.css'%}">
	<title>rules</title>
</head>
<body>
	<form action="{% url 'winit:start' %}" method="POST">
		{% csrf_token %}
		<input type ="hidden" name = "username"	value = "{{username}}">
		<div class = "rule">
			<div class ="log">
				<br>
				<h2>Rules and Conditions</h2>
				<p>1.The essay should be written in English and be NO MORE than 300 words</p>
				<p>2.Do not include any pictures or other illustrations</p>
				<p>3.The essay should be an original piece of work. It should be written in the pupils own words and not copied from any books, articles, or from the internet</p>
				<p>4.High quality examples</p>
				<p>5.Include a purposeful conclusions</p>
				<p>6.Results will be announced on the comming weekend</p>
			</div>
			<div class ="sub">
				<!-- <form action="#" onsubmit="if(document.getElementById('agree').checked) { return true; } 
				else { alert('Please indicate that you have read and agree to the Terms and Conditions '); return false; }">
				{% csrf_token %}
 -->
				<input type="checkbox" name="checkbox" value="check" id="agree" required/> I have read and agree to the Terms and Conditions 
				<br><br><input type="submit" name="submit" value="submit" />

				<!-- </form> -->
				<!-- <input type="submit" name="submit" value="start"> -->
			</div> 
		</div>
</body>
</form>
</html>

mysite/templates/competitions.html
<!-- Latest compiled and minified CSS -->
<html>
<head>
	{%load staticfiles%}
<link rel="stylesheet" href="{%static 'winit/Css/bootstrap.min.css'%}">

<!-- jQuery library -->
<script src="{%static 'winit/Js/jquery.min.js'%}"></script>

<!-- Latest compiled JavaScript -->
<script src="{%static 'winit/Js/bootstrap.min.js'%}"></script>
	<link rel = "stylesheet" type = "text/css" href="{%static 'winit/Css/stylecompetitionspage.css'%}">
</head>
<body>
	<div class= "title" >
		<h1>COMPETITIONS</h1>
	</div>
	<div class="m1">
		<div class= "main" >
			<div class = "maintext">
				<img src = "{%static 'winit/Images/11.jpg'%}">
				<div class = "text">			
					<p>Why compete? In order to succeed, people must compete. Competition can bring out the best in everyone. During a single day, people in some way compete with themselves or with others.Competitions are about a lot more than great prizes and having fun. They allow participants to learn, show their certified skills, compare their results and share their talents with employers.</p></div>
			</div>
			<div class="firstimg">
				<img src= "{%static 'winit/Images/12.jpg'%}" onclick="location='http://www.fedex.com/in/'"></div>
		<!-- 	<div class = "secndimg">
			<img src= "13.png" onclick="location='https://sqore.com/'"></div> -->
		</div>
		<div class="secondmain">
			<p>HOES DOES IT WORK?</p>
			<br>
			<p>Register yourself at our WIN IT <a href="signup.html">SIGN UP</a> page and compete with others in the essay writing competition.The Analytical Writing measure tests your critical thinking and analytical writing skills. It assesses your ability to articulate and support complex ideas, construct and evaluate arguments, and sustain a focused and coherent discussion.</p>
			<br>
			<p> It does not assess specific content knowledge.The Issue task presents an opinion on an issue of general interest followed by specific instructions on how to respond to that issue. You are required to evaluate the issue, consider its complexities and develop an argument with reasons and examples to support your views.</p>
			<br>
			<p>you to construct your own argument by taking a position and providing evidence supporting your views on an issue, and the other requires you to evaluate someone else's argument by assessing its claims and evaluating the evidence it provides.</p><br>
			<p>You are expected to complete the task in 30 minutes and you essay will be evaluated by our panelists.Top 10 best essays will be displayed on our website.Follow Us on <a href="winnerpage.html">Winner's Page</a> on which polling will be conducted.Every individual who visits our site can read the top 10 essays and give their votes to the best one as per their choice.And final results will be declared by the end of every weekend.Stay Tuned for you results.</p><br>
			<p>One best Essay with highest votes will be declared Winner Of the weekly competition.</p>
		</div>
	</div>
</body>
</html>

mysite/templates/disclaimer.html
<html>
<head>
	{%load staticfiles%}
<link rel="stylesheet" href="{%static 'winit/Css/bootstrap.min.css'%}">

<!-- jQuery library -->
<script src="{%static 'winit/Js/jquery.min.js'%}"></script>

<!-- Latest compiled JavaScript -->
<script src="{%static 'winit/Js/bootstrap.min.js'%}"></script>
<link rel = "stylesheet" type = "text/css" href="{%static 'winit/Css/styledisclaimerpage.css'%}">
</head>
<body >
	<div class="homepage" >
		<button type="button" class="btn btn-link btn-lg" ><a href="/">Home Page</a></button>
	</div>
	<div class= "title">
		<h2>DISCLAIMER</h2>
	</div>
	<div class = "main">
		<p>Any content on this website is solely for informational purpose. It does not constitute professional advice or a formal recommendation. While due care has been taken in posting information, the existence of omissions herein is not ruled out. Neither the author nor winit.com accepts any liabilities for any loss or damage of any kind arising out of any inaccurate or incomplete information on this website nor for any actions taken in reliance thereon. No part of posts on this website should be distributed or copied (except for personal, non-commercial use) without express written permission of knowledgesteez.com.</p>
	</div>
	<div class = "lastone">
		<div class="btn-group">
		  <button type="button" class="btn btn-link btn-xs" ><a href="/winit/tc/"> Terms And Conditions |</a></button>
		  <button type="button" class="btn btn-link btn-xs" ><a href="/winit/disc/"> Disclaimer |</a></button>
		  <button type="button" class="btn btn-link btn-xs"> About Us </button></div>
	</div>
</body>
</html>

mysite/templates/exam.html
<html>
<head>	 
	{%load staticfiles%}
	<link rel = "stylesheet" href="{%static 'winit/Css/exam.css'%}">
	<script type = "text/javascript" src ="jquery-1.4.4.min.js"></script>
	<script src ="{%static 'winit/Js/timer.js'%}"></script>
</head>
<body >
	<div id = "timer" >
		Timer:<p id ='time'></p>		
	</div>
	<form action="/winit/answer/" method="POST">
		{% csrf_token %}
	<div class = "log" >
		<input type ="hidden" name = "username"	value = "{{username}}">
			<div class = "ques">
				<div class="questions">
			{% if question %}
    <ul>
		    {% for question1 in question %}
		    <input type ="hidden" name = "qno"	value = "{{ question1.queno}}">

		        {{ question1.question}}
		    {% endfor %}
		    </ul>
		{% else %}
		    <p>No polls are available.</p>
		{% endif %}
		</div>
			</div>
		Answer Here:<textarea name = "essay" rows="4" cols="50"></textarea><br><br>
		<input name="submit" id= "submit" type="submit" value=" submit ">
	</div>

</form>
</body>
</html>

mysite/templates/forgot.html
<html>
<head>
	<link rel = "stylesheet" type = "text/css" href="forgot.css">
	<title>forgot page</title>
</head>
<body topmargin="250" leftmargin="500">
	<form action="" method="">
	<div class = "log">
		E-MAIL:<input hspace="40" type="email" name="usremail"><br><br>
		New-password:<input hspace="10" id="password" name="password"  type="password"><br><br>
		Re-Type password:<input hspace="10" id="password" name="password"  type="password"><br><br>
		<input name="submit" type="submit" value=" send ">
	</div>
</body>
</html>

mysite/templates/login.html
<html>
<head>
	<link rel = "stylesheet" type = "text/css" href="login.css">
	<title>login page</title>
</head>
<body topmargin="250" leftmargin="500">
	<form action="" method="">
		<div class="log">
		<h2>LOGIN HERE</h2>
		E-mail:<input hspace="25"type="email" name="usermail"><br><br>
		password:<input hspace="10" id="password" name="password"  type="password">
		<br><br>
		
		<label><input type="checkbox"> Remember me</label>
		<input hspace="120" name="submit" type="submit" value=" login ">
		<br>

		<a href="forgot.html"><h3 >Forgot your password ?</h3></a>
	</div>
</form>
</body>
</html>

mysite/templates/mystyle.html
<!-- Latest compiled and minified CSS -->
<html>
<head>
	{%load staticfiles%}
<link rel="stylesheet" href="{%static 'winit/Css/bootstrap.min.css'%}">

<!-- jQuery library -->
<script src="{%static 'winit/Js/jquery.min.js'%}"></script>

<!-- Latest compiled JavaScript -->
<script src="{%static 'winit/Js/bootstrap.min.js'%}"></script>
	<link rel = "stylesheet" type = "text/css" href="{%static 'winit/Css/styles.css'%}">
</head>
<body>
	<div class = "main">
		<div class = "title">
			<div class = "titles_img">
				<img src ="{%static 'winit/Images/1.jpg'%}" width = "100%" height="20%"></div>
			<div class = "icon_comp">
				<img src="{%static 'winit/Images/logo.png'%}" width = "75%" ></div>
			<div class = "pins" >
				<div class="btn-group">
				  <button type="button" class="btn btn-link btn-lg"><a href="/winit/comp/">COMPETITIONS</a></button>
				  <button type="button" class="btn btn-link btn-lg"> ABOUT US </button>
				  <button type="button" class="btn btn-link btn-lg">WINNER'S GALLERY</button></div>			
			</div>	
			<div class = "status" align="right">
				<div class = "login">
					<a href = "/winit/signin"><img src= "{%static 'winit/Images/7.png'%}"  width = "85%" height ="6%"></a>
				</div>
				<div class = "sign_up">
					<a href = "/winit/registered"><img src = "{%static 'winit/Images/8.png'%}" width = "85%" height ="6%">
					</a>
				</div>
			</div>	
		</div>
		<div class = "mainbody">
			<img src = "{%static 'winit/Images/9.jpg'%}" width="100%"></div>		
		<div class = "body">
			<div class="btn-group">

			  <button type="button" class="btn btn-link btn-md"> <a href="/winit/tc/">Terms And Conditions |</a></button>
			  <button type="button" class="btn btn-link btn-md"> <a href="/winit/disc/"> Disclaimer |</button>
			  <button type="button" class="btn btn-link btn-md"> About Us </button>
			</div>	
		</div> 
	</div>
</body>
</html>

mysite/templates/signin.html
<html>
<head>
	{%load staticfiles%}
	
	<link rel = "stylesheet" href="{%static 'winit/Css/style1.css'%}">
	<!--script src="{%static 'winit/Js/signup.js'%}"></script>-->
	<title>signin page</title>
</head>
<body background="signup.jpg">
	<form name = "signIn" action = "/winit/signin/" method = "POST">{%csrf_token %}
		<div class = "log">
			<p>{{error}}</p>
			<h2>SIGN IN!!</h2>
			USERNAME:<input id="username" name="username" placeholder="username" type="text" required>
			<br><br>
			PASSWORD:
			<input id="password" name="password" placeholder="**********" type="password" required><br><br>
			<input name="login" type="submit"></a>
		</div>
	</form>
</body>
</html>

mysite/templates/signup.html
<html>
<head>
	{%load staticfiles%}
	<link rel = "stylesheet" href="{%static 'winit/Css/style1.css'%}">
	<script src="{%static 'winit/Js/signup.js'%}"></script>
	<title>signup page</title>
</head>
<body>
	
	<form name="signup" action="/winit/registered/"  method="POST">{%csrf_token %}
	<div class = "log">
		<p>{{error}}</p>
		<h2>SIGNUP AND BECOME A PART OF WIN IT!!</h2>
		FIRSTNAME:<input type = "text" name="fname" id="fname" required><br><br>
		LASTNAME:<input type = "text" name="lname" id = "lname" required><br><br>
		DATE OF BIRTH:<input type = "date"  name="dob" required>
		<br><br>
		ADDRESS:<textarea rows="4" id = "address"name="addr"cols="50" required></textarea><br><br>
		E-MAIL:<input type="email" id = "mailid" name="usremail" required><br><br>
		USERNAME:<input id="name" name="username" placeholder="username" type="text" required>
		<br><br>
		PASSWORD:
		<input id="password" name="password" placeholder="**********" type="password" required>
		<br><br>
		CONFIRM PASSWORD:
		<input id="cpassword" name="cpassword" placeholder="**********" type="password" required>
		<br><br>
		CONTACT NUMBER:<input type = "text" name = "number"id ="pno" required><br><br>

		<input name="submit" type="submit" onclick="myFunction()">
	</div>
	</form>
</body>
</html>

mysite/templates/start.html
<html>
<head>
	{%load staticfiles%}
	<link rel = "stylesheet" href="{%static 'winit/Css/start.css'%}">

	<title>start page </title>
	
	<script type = "text/javascript" src ="jquery-1.4.4.min.js"></script>
	 

  
</head>
<body topmargin="250" leftmargin="500">
	<form action="exam/" method = "POST">
		{%csrf_token %}
<div class = "log">
			<h2>Select Any Topic Here  </h2>
			Topic: 
			<select name="questions">
			<option value="Categories">Categories</option>
    		<option value="General">General</option>
    		<option value="Indian History">Indian History</option>
    		<option value="current affairs">current affairs</option>
    		<option value="Education">Education</option>
  
  			</select>
  			<br><br>

			<input type ="hidden" name = "username"	value = "{{username}}">
		<input name="submit" type="submit" value=" start ">
	</div>
</form>
</body>
</html>

mysite/templates/thanku.html
<html>
<head>
	{%load staticfiles%}
	<link rel = "stylesheet"  href="{%static 'winit/Css/exam.css'%}">
	<script type = "text/javascript" src ="jquery-1.4.4.min.js"></script>
</head>
<body > <!-- topmargin="250" leftmargin="500"> -->
	<form action="" method="POST">
		{% csrf_token %}
		<div class = "log">
			<h3><font color="white"> Thank you for your participation</font></h3>
			<p><font color="white"> We will get back to you with the results by the following Weekend</font></p><br><br>
			<a href="Register.html"><input type="submit" type="submit" value="Home"></a>
			<input type="submit" type="submit" value="logout">
		</div>
	</form>
</body>
</html>

mysite/winit/templates/winit/signup.html
<!-- <html>
<head>
	<link rel = "stylesheet" type = "text/css" href="style1.css">
	<title>signup page</title>
</head>
<body>
	<form action="" method="">
	<div class = "log">
		
		<h2>LOGIN HERE</h2>
		FIRSTNAME:<input type = "text" id="fname" ><br><br>
		LASTNAME:<input type = "text" id = "lname" ><br><br>
		DATE OF BIRTH:
		<select name="month">
			<option>-Month-</option>
			<option value="jan">january</option>
			<option value="feb">febuary</option>
			<option value="march">march</option>
			<option value="apr">april</option>
			<option value="may">may</option>
			<option value="june">june</option>
			<option value="july">july</option>
			<option value="aug">august</option>
			<option value="sept">september</option>
			<option value="oct">october</option>
			<option value="nov">november</option>
			<option value="dec">december</option>
		</select>
		<select name="date">
			<option>-Date-</option>
			<option value="1">1</option>
			<option value="2">2</option>
			<option value="3">3</option>
			<option value="4">4</option>
			<option value="5">5</option>
			<option value="6">6</option>
			<option value="7">7</option>
			<option value="8">8</option>
			<option value="9">9</option>
			<option value="10">10</option>
			<option value="11">11</option>
			<option value="12">12</option>
			<option value="13">13</option>
			<option value="14">14</option>
			<option value="15">15</option>
			<option value="16">16</option>
			<option value="17">17</option>
			<option value="18">18</option>
			<option value="19">19</option>
			<option value="20">20</option>
			<option value="21">21</option>
			<option value="22">22</option>
			<option value="23">23</option>
			<option value="24">24</option>
			<option value="25">25</option>
			<option value="26">26</option>
			<option value="27">27</option>
			<option value="28">28</option>
			<option value="29">29</option>
			<option value="30">30</option>
			<option value="31">31</option>
			

			
		</select>
		<select name="year">
			<option>-Year-</option>
			<option value="1985">1985</option>
			<option value="1986">1986</option>
			<option value="1987">1987</option>
			<option value="1988">1988</option>
			<option value="1989">1989</option>
			<option value="1990">1990</option>
			<option value="1991">1991</option>
			<option value="1992">1992</option>
			<option value="1993">1993</option>
			<option value="1994">1994</option>
			<option value="1995">1995</option>
			<option value="1996">1996</option>
			<option value="1997">1997</option>
			<option value="1998">1998</option>
			<option value="1999">1999</option>
			<option value="2000">2000</option>
			<option value="2001">2001</option>
			<option value="2002">2002</option>
			<option value="2003">2003</option>
			<option value="2004">2004</option>
			<option value="2005">2005</option>
		</select>


		<br><br>
		ADDRESS:<textarea rows="4" cols="50"></textarea><br><br>
		 email:<input id="name" name="username" placeholder="username" type="text">
<br><br>
		 E-MAIL:<input type="email" name="usremail"><br><br>
		USERNAME:<input id="name" name="username" placeholder="username" type="text">
		<br><br>
		PASSWORD:
		<input id="password" name="password" placeholder="**********" type="password">
		<br><br>
		CONFORM PASSWORD:
		<input id="cpassword" name="cpassword" placeholder="**********" type="password">
		<br><br>
		CONTACT NUMBER:<input type = "text" id ="pno"><br><br>

		<input name="submit" type="submit" value=" submit ">

		<input name="submit" type="submit" value=" Reset ">
		
		
	

	</div>
</form>
</body>
</html>

 --> 
 <h1>{{title}}</h1>
 <form method='POST' action="">{%csrf_token %}
 {{form.as_p}}
 <input type='submit' value='submit'/>
</form>