mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^winit/', include('winit.urls', namespace="winit")),
    url(r'^$', 'winit.views.home',name='home'),
    url(r'^admin/', include(admin.site.urls)),

]
# from django.conf.urls import patterns, include, url


# urlpatterns = patterns('',
#    url(r'^$', include('winit.urls', namespace="winit", app_name="winit")),
# )

winit/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('',
   url(r'^$', 'winit.views.home', name='home'),
   url(r'^comp/$', 'winit.views.comp', name='comp'),
   url(r'^tc/$','winit.views.tc',name='tc'),
   url(r'^disc/$','winit.views.disc',name='disc'),
   url(r'^registered/$', 'winit.views.store', name='store'),

   url(r'^signin/$','winit.views.check', name='checkin'),
   url(r'^start/$','winit.views.start', name='start'),
   url(r'^start/exam/$','winit.views.exam', name='exam'),
   url(r'^thanku/$','winit.views.thanku',name='thanku'),
   url(r'^answer/$','winit.views.answer',name='answer')   

   
   

templates/Register.html
<!-- Latest compiled and minified CSS -->
<html>
<head>
<link rel="stylesheet" href="bootstrap.min.css">

<!-- jQuery library -->
<script src="jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="bootstrap.min.js"></script>


	<link rel = "stylesheet" type = "text/css" href="styles.css">
</head>
<body>
<<<<<<< HEAD

=======
>>>>>>> 214f5e505f066e8928b8c039fa1209fd1b263aae
	<div class = "main">
		<div class = "title">
			<div class = "titles_img">
				<img src ="1.jpg" width = "100%" height="25%"></div>
			<div class = "icon_comp">
				<img src="winit.gif" width="60%" height="20%"></div>
			<div class = "pins" >
				<div class="btn-group">
				  <button type="button" class="btn btn-link btn-lg">COMPETITIONS</button>
				  <button type="button" class="btn btn-link btn-lg"> ABOUT US </button>
				  <button type="button" class="btn btn-link btn-lg">WINNER'S GALLERY</button></div>			
			</div>	
			<div class = "status" align="right">
				<div class = "login">
						<a href = "login.html"><img src= "7.png" width = "85%" height ="6%"></a>
				</div>
				<div class = "sign_up">
					<a href = "signup.html"><img src = "8.png" width = "85%" height ="6%">
					</a>
				</div>
			</div>	
		</div>
		<div class = "mainbody">
			<img src = "9.jpg" width="100%"></div>		
			<div class = "body">
				<div class="btn-group">
				  <button type="button" class="btn btn-link btn-lg"> Terms And Conditions |</button>
				  <button type="button" class="btn btn-link btn-lg"> Disclaimer |</button>
				  <button type="button" class="btn btn-link btn-lg"> About Us </button></div>	
			</div> 

	</div>
</body>
</html>

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <title>Django Login Application |
        {% block title %}{% endblock %}</title>
    </head>
    <body>
        <h1>{% block head %}{% endblock %}</h1>
        {% block content %}{% endblock %}
 
    </body>
</html>

templates/exam.html
<html>
<head>	 
	{%load staticfiles%}
	<link rel = "stylesheet" href="{%static 'winit/Css/exam.css'%}">
	<script type = "text/javascript" src ="jquery-1.4.4.min.js"></script>
	<script src ="{%static 'winit/Js/timer.js'%}"></script>
</head>
<body >
	<div id = "timer" >
		Timer:<p id ='time'></p>		
	</div>

	<form action="/winit/answer/" method="POST">
		{% csrf_token %}

<!-- 	<form action="{% url 'winit:thanku' %}" method="">

	<form action="thanku.html" method=""> -->

	<div class = "log" >
		<input type ="hidden" name = "username"	value = "{{username}}">
			<div class = "ques">
				<div class="questions">
			{% if question %}
    <ul>
		    {% for question1 in question %}
		    <input type ="hidden" name = "qno"	value = "{{ question1.queno}}">

		        {{ question1.question}}
		    {% endfor %}
		    </ul>
		{% else %}
		    <p>No polls are available.</p>
		{% endif %}
		</div>
			</div>
		Answer Here:<textarea name = "essay" rows="4" cols="50"></textarea><br><br>
		<input name="submit" id= "submit" type="submit" value=" submit ">
	</div>

</form>
</body>
</html>

templates/signin.html
<html>
<head>
	{%load staticfiles%}
<<<<<<< HEAD
	
=======
<<<<<<< HEAD
	
=======
>>>>>>> 214f5e505f066e8928b8c039fa1209fd1b263aae
>>>>>>> cf3e7bb7c426f48ff3c6b4e61ef3aba23ab5ec56
	<link rel = "stylesheet" href="{%static 'winit/Css/style1.css'%}">
	<!--script src="{%static 'winit/Js/signup.js'%}"></script>-->
	<title>signin page</title>
</head>
<<<<<<< HEAD
<body background="signup.jpg">
=======
<<<<<<< HEAD
<body background="signup.jpg">
=======
<body>
>>>>>>> 214f5e505f066e8928b8c039fa1209fd1b263aae
>>>>>>> cf3e7bb7c426f48ff3c6b4e61ef3aba23ab5ec56
	<form name = "signIn" action = "/winit/signin/" method = "POST">{%csrf_token %}
		<div class = "log">
			<p>{{error}}</p>
			<h2>SIGN IN!!</h2>
			USERNAME:<input id="username" name="username" placeholder="username" type="text" required>
			<br><br>
			PASSWORD:
			<input id="password" name="password" placeholder="**********" type="password" required><br><br>
			<input name="login" type="submit"></a>
		</div>
	</form>
</body>
</html>

templates/signup.html
<html>
<head>
	{%load staticfiles%}
	<link rel = "stylesheet" href="{%static 'winit/Css/style1.css'%}">
	<script src="{%static 'winit/Js/signup.js'%}"></script>
	<title>signup page</title>
</head>
<body>
	
	<form name="signup" action="/winit/registered/"  method="POST">{%csrf_token %}
	<div class = "log">
		<p>{{error}}</p>

		<h2>SIGNUP AND BECOME A PART OF WIN IT!!</h2>
		FIRSTNAME:<input type = "text" name="fname" id="fname" required><br><br>
		LASTNAME:<input type = "text" name="lname" id = "lname" required><br><br>
		DATE OF BIRTH:<input type = "date"  name="dob" required>
		<br><br>
		ADDRESS:<textarea rows="4" id = "address"name="addr"cols="50" required></textarea><br><br>
		E-MAIL:<input type="email" id = "mailid" name="usremail" required><br><br>
		USERNAME:<input id="name" name="username" placeholder="username" type="text" required>
		<br><br>
		PASSWORD:
		<input id="password" name="password" placeholder="**********" type="password" required>
		<br><br>
		CONFIRM PASSWORD:
		<input id="cpassword" name="cpassword" placeholder="**********" type="password" required>
		<br><br>
		CONTACT NUMBER:<input type = "text" name = "number"id ="pno" required><br><br>

		<input name="submit" type="submit" onclick="myFunction()">
	</div>
	</form>
</body>
</html>

templates/thanku.html
<html>
<head>
	{%load staticfiles%}
	<link rel = "stylesheet"  href="{%static 'winit/Css/exam.css'%}">
	<script type = "text/javascript" src ="jquery-1.4.4.min.js"></script>
</head>
<body > <!-- topmargin="250" leftmargin="500"> -->
	<!-- <form action="" method="POST"> -->
		{% csrf_token %}
		<div class = "log">
			<h3><font color="white"> Thank you for your participation</font></h3>
			<p><font color="white"> We will get back to you with the results by the following Weekend</font></p><br><br>
			<input type="submit" type="submit" value="Home" onclick ="location ='/'">
			<input type="submit" type="submit" value="logout">
		</div>
	<!-- </form> -->
</body>
</html>